/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trafficvolume;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author user
 */
public class UiApplication extends javax.swing.JFrame {
    private LinearRegressionML lr;
    private int clsIdx;
    /**
     * Creates new form UiApplication
     */
    public UiApplication() {
        initComponents();
    }
    public UiApplication(LinearRegressionML lr, int classIndex) {
        this.lr = lr;
        this.clsIdx = classIndex;
        initComponents();
    }
    
    private double predictInstance(){
        
        String holiday = (String) this.holidayCB.getSelectedItem();
        HashMap<String, Object> holidayMap = new HashMap<>();
        holidayMap.put("value", holiday);
        holidayMap.put("type", "String");
        
        double temp = Double.parseDouble(this.tempTF.getText());
        HashMap<String, Object> tempMap = new HashMap<>();
        tempMap.put("value", temp);
        tempMap.put("type", "double");
        
        double rain1Hr = Double.parseDouble(this.rainTF.getText());
        HashMap<String, Object> rainMap = new HashMap<>();
        rainMap.put("value", rain1Hr);
        rainMap.put("type", "double");
        
        double snow1Hr = Double.parseDouble(this.snowTF.getText());
        HashMap<String, Object> snowMap = new HashMap<>();
        snowMap.put("value", snow1Hr);
        snowMap.put("type", "double");
        
        double cloudsAll = Double.parseDouble(this.cloudTF.getText());
        HashMap<String, Object> cloudMap = new HashMap<>();
        cloudMap.put("value", cloudsAll);
        cloudMap.put("type", "double");
        
        String weatherDescription = (String) this.weatherDescCB.getSelectedItem();
        HashMap<String, Object> weatherDescMap = new HashMap<>();
        weatherDescMap.put("value", weatherDescription);
        weatherDescMap.put("type", "String");
        
        String dayTime = (String) this.dayTimeCB.getSelectedItem();
        HashMap<String, Object> dayTimeMap = new HashMap<>();
        dayTimeMap.put("value", dayTime);
        dayTimeMap.put("type", "String");
        
        ArrayList<HashMap<String, Object>> list = new ArrayList<>();
        list.add(holidayMap);
        list.add(tempMap);
        list.add(rainMap);
        list.add(snowMap);
        list.add(cloudMap);
        list.add(weatherDescMap);
        list.add(dayTimeMap);
        double ans = this.lr.predictOneInstance("predict.arff", this.clsIdx, list);
        return ans;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tempTF = new javax.swing.JTextField();
        rainTF = new javax.swing.JTextField();
        snowTF = new javax.swing.JTextField();
        cloudTF = new javax.swing.JTextField();
        holidayCB = new javax.swing.JComboBox<>();
        weatherDescCB = new javax.swing.JComboBox<>();
        dayTimeCB = new javax.swing.JComboBox<>();
        predictBtn = new javax.swing.JButton();
        predictTxtArea = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Temperature: ");

        jLabel2.setText("Rain Amount (mm): ");

        jLabel3.setText("Snow Amount (mm): ");

        jLabel4.setText("Holiday: ");

        jLabel5.setText("Clouds Percent (mm): ");

        jLabel6.setText("Weather Description: ");

        jLabel7.setText("Day Time: ");

        tempTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTFActionPerformed(evt);
            }
        });

        holidayCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Columbus Day", "Labor Day", "Washingtons Birthday", "Independence Day", "Christmas Day", "Thanksgiving Day", "Memorial Day", "Veterans Day" }));

        weatherDescCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "light rain", "sky is clear", "mist", "overcast clouds", "scattered clouds", "fog", "drizzle", "thunderstorm", "moderate rain", "broken clouds", "light snow", "light intensity drizzle", "few clouds", "proximity thunderstorm", "Sky is Clear", "haze", "heavy snow", "proximity shower rain", "very heavy rain", "heavy intensity rain", "heavy intensity drizzle", "snow", "smoke", "thunderstorm with light rain", "proximity thunderstorm with rain", "thunderstorm with rain", "light shower snow", "SQUALLS", "thunderstorm with heavy rain", "light intensity shower rain", "proximity thunderstorm with drizzle", "thunderstorm with light drizzle", "shower snow" }));

        dayTimeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday 4:00", "Saturday 13:00", "Friday 4:00", "Saturday 20:00", "Monday 12:00", "Friday 3:00", "Saturday 0:00", "Thursday 4:00", "Wednesday 8:00", "Thursday 5:00", "Thursday 17:00", "Friday 9:00", "Wednesday 4:00", "Thursday 16:00", "Monday 20:00", "Friday 15:00", "Sunday 15:00", "Saturday 2:00", "Thursday 11:00", "Wednesday 21:00", "Wednesday 16:00", "Sunday 16:00", "Wednesday 22:00", "Tuesday 4:00", "Sunday 6:00", "Monday 9:00", "Monday 2:00", "Saturday 10:00", "Sunday 8:00", "Friday 0:00", "Friday 21:00", "Sunday 3:00", "Monday 3:00", "Saturday 23:00", "Wednesday 7:00", "Friday 23:00", "Tuesday 22:00", "Thursday 18:00", "Monday 11:00", "Saturday 5:00", "Sunday 17:00", "Saturday 6:00", "Thursday 1:00", "Tuesday 8:00", "Wednesday 17:00", "Tuesday 23:00", "Friday 2:00", "Wednesday 0:00", "Saturday 7:00", "Sunday 10:00", "Thursday 0:00", "Friday 11:00", "Friday 12:00", "Thursday 23:00", "Tuesday 11:00", "Tuesday 19:00", "Wednesday 9:00", "Wednesday 18:00", "Tuesday 20:00", "Saturday 11:00", "Monday 14:00", "Friday 6:00", "Tuesday 16:00", "Sunday 19:00", "Saturday 12:00", "Sunday 21:00", "Wednesday 6:00", "Monday 0:00", "Tuesday 9:00", "Monday 22:00", "Thursday 13:00", "Friday 18:00", "Thursday 15:00", "Wednesday 5:00", "Friday 5:00", "Thursday 7:00", "Tuesday 17:00", "Friday 17:00", "Thursday 8:00", "Sunday 7:00", "Tuesday 5:00", "Sunday 11:00", "Friday 8:00", "Friday 19:00", "Friday 7:00", "Saturday 21:00", "Saturday 9:00", "Saturday 15:00", "Thursday 19:00", "Sunday 12:00", "Sunday 4:00", "Tuesday 14:00", "Tuesday 2:00", "Monday 7:00", "Tuesday 7:00", "Thursday 22:00", "Thursday 2:00", "Tuesday 0:00", "Saturday 14:00", "Wednesday 1:00", "Sunday 14:00", "Wednesday 23:00", "Wednesday 20:00", "Friday 20:00", "Tuesday 21:00", "Tuesday 12:00", "Thursday 12:00", "Monday 13:00", "Thursday 6:00", "Sunday 20:00", "Sunday 2:00", "Wednesday 13:00", "Sunday 22:00", "Sunday 13:00", "Wednesday 11:00", "Monday 10:00", "Sunday 9:00", "Tuesday 1:00", "Saturday 17:00", "Saturday 18:00", "Wednesday 3:00", "Tuesday 15:00", "Thursday 10:00", "Monday 21:00", "Friday 14:00", "Sunday 5:00", "Friday 13:00", "Monday 19:00", "Wednesday 19:00", "Monday 5:00", "Tuesday 6:00", "Saturday 8:00", "Monday 8:00", "Sunday 18:00", "Saturday 19:00", "Thursday 3:00", "Tuesday 18:00", "Tuesday 13:00", "Thursday 14:00", "Friday 10:00", "Monday 16:00", "Saturday 16:00", "Wednesday 15:00", "Saturday 22:00", "Monday 6:00", "Monday 17:00", "Wednesday 2:00", "Thursday 21:00", "Saturday 4:00", "Monday 1:00", "Wednesday 10:00", "Tuesday 10:00", "Friday 22:00", "Saturday 1:00", "Friday 1:00", "Friday 16:00", "Monday 23:00", "Sunday 23:00", "Wednesday 12:00", "Sunday 1:00", "Thursday 9:00", "Tuesday 3:00", "Sunday 0:00", "Saturday 3:00", "Wednesday 14:00", "Monday 15:00", "Thursday 20:00", "Monday 18:00" }));

        predictBtn.setText("Predict");
        predictBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                predictBtnMouseClicked(evt);
            }
        });

        jLabel8.setText("Traffic Volume Application 1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(93, 93, 93)
                                        .addComponent(holidayCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dayTimeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(weatherDescCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(206, 206, 206)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rainTF)
                            .addComponent(tempTF, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(snowTF)
                            .addComponent(cloudTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(predictTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(predictBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(tempTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holidayCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(rainTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weatherDescCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(snowTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayTimeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cloudTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(predictBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(predictTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempTFActionPerformed

    private void predictBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_predictBtnMouseClicked
        // TODO add your handling code here:
        double ans = this.predictInstance();
        this.predictTxtArea.setText(Double.toString(ans));
    }//GEN-LAST:event_predictBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UiApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UiApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UiApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UiApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UiApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cloudTF;
    private javax.swing.JComboBox<String> dayTimeCB;
    private javax.swing.JComboBox<String> holidayCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton predictBtn;
    private javax.swing.JTextField predictTxtArea;
    private javax.swing.JTextField rainTF;
    private javax.swing.JTextField snowTF;
    private javax.swing.JTextField tempTF;
    private javax.swing.JComboBox<String> weatherDescCB;
    // End of variables declaration//GEN-END:variables

    public LinearRegressionML getLr() {
        return lr;
    }

    public void setLr(LinearRegressionML lr) {
        this.lr = lr;
    }

    public int getClsIdx() {
        return clsIdx;
    }

    public void setClsIdx(int clsIdx) {
        this.clsIdx = clsIdx;
    }
}
